server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      #instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}
      instanceId: ${spring.application.name}:${server.port}
    preferIpAddress: true
  registration:
    enabled: true


endpoints:
  restart:
    enabled: true
  shutdown:
    enabled: true
  health:
    sensitive: false
