#server:
#  port: 8762
#spring:
#  application:
#    name: server-01
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8762/eureka/
#  instance:
#    metadataMap:
#      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}